# Site settings
title: ZhengZhiKun
email: admin@akunsoft.com
description: > # this means to ignore newlines until "baseurl:"
  一只前端领域的小小鸟，正在逐渐成长
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhengzhikun.cn" # the base hostname & protocol for your site
github_username:  zhengzk
#highlighter: rouge
highlighter: pygments
encoding: utf-8
# Build settings
markdown: kramdown
encoding: utf-8
